### ISSUE TITLE
Not enough balance to submit a solution.

### ISSUE THREAD

**Issue by PawanRamaMali** [nickyharpor/CrossWeave#1]
I created an account on Arweave, posted the Tweet on Twitter and still not enough balance.

**Comment by nickyharpor** [comment]
@PawanRamaMali it takes a while for Arweave faucet to send funds to your newly created account. Please wait a few hours and check your balance by searching your address in [ViewBlock](https://viewblock.io/arweave). When your balance is greater than zero, try CrossWeave again.

**Comment by PawanRamaMali** [comment]
@nickyharpor  Thank you, It is working now, I just had to wait for the update.
